#!/bin/bash

NODE=$(which node)
PID_FILE="./nodem.pid"

if [ -e "${PID_FILE}" ]; then
    PID=$(cat "${PID_FILE}")
fi

function check_status {
        if [ -e "${PID_FILE}" ]; then
            OUTPUT=$(ps aux | grep ${PID} | grep -v grep)
            if [ "${#OUTPUT}" -gt 0 ] ; then
                echo 0
            else
                echo 1
            fi
        else
            echo 2
        fi
}

case "$1" in
    "start")
        if [ -e "${PID_FILE}" ]; then
            echo "Nodem is already running."
        else
            "${NODE}" ./src/Main.js&
            PID=$!
            echo ${PID} > "${PID_FILE}"
        fi
    ;;

    "stop")
        kill -TERM ${PID}
        rm "${PID_FILE}"
    ;;

    "reload")
        kill -HUP ${PID}
    ;;

    "restart")
        ./nodem stop
        ./nodem start
    ;;

    "status")
        STATUS=$(check_status)
        case "${STATUS}" in
            0)
                echo "Nodem is running."
            ;;

            [1-2])
                echo "Nodem is not running."

                if [ -e ${PID_FILE} ]; then
                    rm ${PID_FILE}
                fi
            ;;
        esac
    ;;

    *)
        echo "Usage: ./nodem (start|stop|restart)"
    ;;
esac